# when push to main or pull request to all branches
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

# test and build
jobs:
  build:
    name: test and build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: execute permission for gradlew
        run: chmod +x gradlew

      - name: do test
        run: ./gradlew clean test

      - name: build
        run: ./gradlew build